### ISSUE TITLE
Exceeding geolocation limits

### ISSUE THREAD

**Issue by nhumber** [dhernandez98/pokespawn#4]
after 300 tweets the script shuts down with this on reboot

PokeSpawn v1.01 - @MrKemula
Traceback (most recent call last):
  File "pokespawn.py", line 279, in <module>
    main()
  File "pokespawn.py", line 62, in main
    PokListener(bot)
  File "pokespawn.py", line 263, in PokListener
    location = geolocator.reverse((pokemon.lat, pokemon.lon), True)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 266, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 363, in _check_status
    'The given key has gone over the requests limit in the 24'
geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.

any idea on a way to fix this or to use something other than googles reverse lookup?

**Comment by nhumber** [comment]
just an update , i feel stupid, i messed around all day and somehow overlooked the API key in the script!

with a few modifications the twitter feed is working great without having to use telegram!! thanks again eh, this is what my "Poke Miner" needed
